config/routes.rb
Rails.application.routes.draw do
  get 'tickets/index'
  get 'tickets/show'
  get 'api/create'
  post '/api/create', to: 'api#create'
  resources :tickets, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
class Excavator < ApplicationRecord
    belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    has_one :excavator
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def create
    file = File.read('sample.json')
    data = JSON.parse(file)
  
    ticket_attributes = ticket_params(data['Ticket']).merge(ticket_params(data['DateTimes'])).merge(ticket_params(data["ExcavationInfo"]["DigsiteInfo"]["WellKnownText"]))
    ticket_attributes[:primary_service_area_code] = data.dig('ServiceArea', 'primary_service_area_code', 'SACode')
    ticket_attributes[:additional_service_area_codes] = data.dig('ServiceArea', 'additional_service_area_codes', 'SACode') || []

    ticket = Ticket.new(ticket_attributes)
    excavator = Excavator.new(excavator_params(data['Excavator']))
    
    if ticket.save
      excavator.ticket_id = ticket.id
      excavator.save
      render json: { message: 'Data saved successfully' }
    else
      render json: { error: 'Data not saved', errors: ticket.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private
  def ticket_params(ticket_data)
    return {} unless ticket_data
  
    ticket_data.slice(
      'request_number', 'sequence_number', 'request_type', 'request_action',
      'response_due_datetime', 'primary_service_area_code','additional_service_area_codes', 'well_known_text'
    )&.transform_keys { |key| key.underscore.to_sym } || {}
  end
  
  def excavator_params(excavator_data)
    excavator_data.slice('company_name', 'address', 'crew_on_site')&.transform_keys { |key| key.underscore.to_sym } || {}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end

  def show
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExcavationApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/index.html.erb
<h1>Ticket List</h1>

<table>
  <thead>
    <tr>
      <th>Request Number</th>
      <th>Request Type</th>
      <th>Request Action</th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.request_number %></td>
        <td><%= ticket.request_type %></td>
        <td><%= ticket.request_action %></td>
        <td><%= link_to 'View', ticket_path(ticket) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/show.html.erb
<h1>Ticket Details</h1>

<table>
  <tr>
    <th>Request Number:</th>
    <td><%= @ticket.request_number %></td>
  </tr>
  <tr>
    <th>Sequence Number:</th>
    <td><%= @ticket.sequence_number %></td>
  </tr>
  <tr>
    <th>Request Type:</th>
    <td><%= @ticket.request_type %></td>
  </tr>
  <tr>
    <th>Request Action:</th>
    <td><%= @ticket.request_action %></td>
  </tr>
  <tr>
    <th>Response Due Date Time:</th>
    <td><%= @ticket.response_due_datetime %></td>
  </tr>
  <tr>
    <th>Primary Service Area Code:</th>
    <td><%= @ticket.primary_service_area_code %></td>
  </tr>
  <tr>
    <th>Additional Service Area Codes:</th>
    <td><%= @ticket.additional_service_area_codes %></td>
  </tr>
  <tr>
    <th>Digsite Info - Well Known Text:</th>
    <td><%= @ticket.well_known_text %></td>
  </tr>
  <tr>
    <th>Excavator - Company Name:</th>
    <td><%= @ticket.excavator.company_name %></td>
  </tr>
  <tr>
    <th>Excavator - Address:</th>
    <td><%= @ticket.excavator.address %></td>
  </tr>
  <tr>
    <th>Excavator - Crew On Site:</th>
    <td><%= @ticket.excavator.crew_on_site ? 'Yes' : 'No' %></td>
  </tr>
</table>

<div id="osm-map"></div>

<script>
// Where you want to render the map.
var element = document.getElementById('osm-map');

// Height has to be set. You can do this in CSS too.
element.style = 'height:300px;';

// Create Leaflet map on map element.
var map = L.map(element);

// Add OSM tile layer to the Leaflet map.
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

// Target's GPS coordinates.
var target = L.latLng('47.50737', '19.04611');

// Set map's center to target with zoom 14.
map.setView(target, 14);

// Place a marker on the same location.
L.marker(target).addTo(map);
</script>